#!/usr/bin/env bash

set -e

CACHE_DIR="/home/pi/.cache/mopidy/youtube"
CURRENT_STATUS_FILE="/home/pi/.local/share/mopidy/current_status"
# 5 GB limit:
MAX_DIR_SIZE="$((1024 * 1024 * 5000))"

function remove_old_youtube_cache() {
    # https://stackoverflow.com/questions/11618144/bash-script-to-limit-a-directory-size-by-deleting-files-accessed-last

    # Use last change time %C given that strangely %T provide very old access time
    find "$CACHE_DIR" -type f -printf "%C@::%p::%s\n" \
        | sort -rn \
        | awk -v maxbytes="$MAX_DIR_SIZE" -F "::" '
  BEGIN { curSize=0; }
  {
  curSize += $3;
  if (curSize > maxbytes) { print $2; }
  }
  ' \
        | tac | xargs -r -I {} rm --verbose {}

    return 0
}

function restore_status() {
    if [[ ! -e $CURRENT_STATUS_FILE ]]
    then
        return 0
    fi
    # sed command ensure there are no spaces between colon
    statuses=($(cat $CURRENT_STATUS_FILE | grep volume | sed -e 's/ *: */:/g' -e 's/%//g' ))
    for status in "${statuses[@]}"
    do
        mpc $(echo $status | sed 's/:/ /g')
    done
}

echo Restoring the previous playlist in current-playlist
mpc clear
mpc load current-playlist || echo mpc load failed
restore_status
echo Restored the playlist from current-playlist.

echo Removing old Youtube cache files...
remove_old_youtube_cache
echo Removed old Youtube cache files

echo Sleeping for 3600 secs...
sleep 3600

while true
do
    echo Saving the current playlist to current-playlist...
    mpc save current-playlist
    mpc status > $CURRENT_STATUS_FILE
    echo Saved the current playlist to current-playlist.
    echo Removing old Youtube cache files...
    remove_old_youtube_cache
    echo Removed old Youtube cache files

    echo Sleeping for 3600 secs...
    sleep 3600
done
